#      This code Generated By me 
def b():
    global l
    l = []
    while True:
        i = input("Enter the number of books :")
        l.append(i)
        
        
        if(i == 'end'):
            break
    return l


class library:
    def __init__(self , book , count):
        self.book = book
        self.count = count

    def display(self):
        for i in range(len(self.book)):
            print(f"Name of Book :{self.book[i]}")
        print(f"The Total number of books are available is {self.count}")

bi = b()
c = len(l)
l = library(bi , c)
l.display()



##### This code is generated by harry
# class l:
#     def __init__(self):
#         self.book = []
#         self.noofbooks = 0

#     def addBook(self , book):
#         self.book.append(book)
#         self.noofbooks = len(self.book)

#     def showinfo(self):
#         print(f"The library has {self.noofbooks}. \n The books ")
#         for book in self.book:
#             print(book)

# l1 = l()
# l1.addBook("Ramayan")
# l1.addBook("mahabharat")
# l1.addBook("python")
# l1.showinfo()